# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thames Punting Club
email: peter@petersharp.org
description: > # this means to ignore newlines until "baseurl:"
  The website of the Thames Punting Club, the governing body of punt racing in the UK. Thames Punting Club was formed in 1885 as a racing club. It is now no longer a racing club but functions as the sport’s governing body.
baseurl: "/thames-punting-club" # the subpath of your site, e.g. /blog
url: "http://mrpsharp.github.io" # the base hostname & protocol for your site
twitter_username: tpc1885
permalinks: pretty
# github_username:  jekyll

sass:
  sass_dir: _sass
  # style: compressed

# Build settings
markdown: kramdown
